language: node_js
node_js:
  - "6"
install:
  - "yarn global add mocha-phantomjs"
  - "yarn install"
before_script:
  - "grunt cssmin uglify"
script:
  - "mocha-phantomjs test/test.html --ignore-ssl-errors=true"
